### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by ian-sayles** [twilio-labs/twilio-firebase-extensions#62]
Tried updating to new updated version, but just get circle progress going round and nothing happens.
Left it for 5 minutes and still not finished, exited then tried again with same issue.

<img width="251" alt="Screenshot 2023-04-26 at 10 39 52" src="https://user-images.githubusercontent.com/4272389/234536708-9283c4c1-5a96-401f-b507-3e3b1e9f5ceb.png">

Do you have to change anything before doing the upgrade?
Anyone else have this issue?

Tried viewing the release notes, but page not found.
https://github.com/firebase/extensions/blob/main/send-message/CHANGELOG.md

Forgot to add:

Current version : twilio/send-message@0.2.1

**Comment by Raketten1963** [comment]
I have the exact same issues, have been waiting patiently half a day....

**Comment by druv5319** [comment]
Working on a fix today. Will close the issue once its pushed.

**Comment by ian-sayles** [comment]
Thanks

**Comment by druv5319** [comment]
Fixed. Previously, Firebase would use the prebuilt functions in the extension when uploaded. A recent update by them made it so Google Cloud Functions runs a `npm run build` by default when deploying extensions and functions.

When `npm run build` is executed, the tsconfig.json file in send-message/functions extends its properties from the tsconfig.json file in the root directory which can only be read if its built locally but cannot be read if its built on GCP since only the send-message directory is deployed rather than the entire repo.

This [commit](https://github.com/twilio-labs/twilio-firebase-extensions/commit/4e88361637103111bebd2a7b11b1ce8d2ed9c13d) fixes the issue by removing the extended properties from the root tsconfig.json and moves them into the /functions tsconfig.json file.

To update/install the new version that fixes the build crash, head over here: https://console.firebase.google.com/project/_/extensions/install?ref=twilio/send-message@0.3.2

**Comment by ian-sayles** [comment]
Thanks for doing the fix, when I try to upgrade from the Firebase Console it is still showing version send-message@0.2.1 not the fixed version 0.3.1.  Will this version be pushed to the console, for if I click the link in the link above it wants to install a new instance of the send-message.
